name:                functional-assignment
version:             0.1.0.0
github:              "liamradley1/functional-assignment"
license:             BSD3
author:              "Liam Radley, Sara Nikamalfard, Hassan Bashir"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/liamradley1/functional-assignment#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- bytestring
- aeson
- HDBC
- HDBC-postgresql

library:
  source-dirs: src

executables:
  functional-assignment-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functional-assignment

tests:
  functional-assignment-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functional-assignment
